name: Publish CFB Rank JSON to Pickem

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch of pickem repo (default: main)"
        required: false
        default: "main"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # ---- PATHS (ranking repo source → pickem repo dest) ----
      SOURCE_JSON: docs/data/rankings.json        # <-- FIXED: lives at repo root/docs/data/rankings.json
      PICKEM_OWNER: dstaggs-15
      PICKEM_REPO: cfb-pickem-model
      TARGET_PATH: docs/data/cfbrank.json         # where the pickem site reads it
      # --------------------------------------------------------

    steps:
      - name: Checkout ranking repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify source rankings.json exists
        run: |
          if [ ! -f "$SOURCE_JSON" ]; then
            echo "ERROR: $SOURCE_JSON not found."
            ls -la docs || true
            ls -la docs/data || true
            exit 1
          fi
          echo "Found $SOURCE_JSON"

      - name: Build cfbrank.json (Top-25 → ranks array + teams map)
        run: |
          # Emits a compact file the pickem frontend understands:
          # {
          #   "season": <int>,
          #   "last_build_utc": "<utc>",
          #   "ranks": [ {"team":"Indiana","rank":1}, ... ],
          #   "teams": { "Indiana":1, ... }
          # }
          jq '{
                season: .season,
                last_build_utc: .last_build_utc,
                ranks: (.top25 | map({team: .team, rank: .rank})),
                teams: (.top25 | map({key: .team, value: .rank}) | from_entries)
              }' "$SOURCE_JSON" > cfbrank.json

          echo "Built cfbrank.json (first lines):"
          head -n 30 cfbrank.json || true

      - name: Checkout pickem repo (target)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PICKEM_OWNER }}/${{ env.PICKEM_REPO }}
          token: ${{ secrets.PICKEM_PUSH_TOKEN }}  # Fine-grained PAT with Contents: Read/Write on pickem repo
          ref: ${{ github.event.inputs.target_branch || 'main' }}
          path: pickem
          fetch-depth: 0

      - name: Copy artifact into pickem repo
        run: |
          mkdir -p "pickem/$(dirname "$TARGET_PATH")"
          cp cfbrank.json "pickem/$TARGET_PATH"
          echo "Copied cfbrank.json -> pickem/$TARGET_PATH"
          ls -l "pickem/$(dirname "$TARGET_PATH")"

      - name: Commit & push if changed
        run: |
          cd pickem
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "$TARGET_PATH" || true
          if git diff --cached --quiet; then
            echo "No changes to commit. Exiting."
            exit 0
          fi

          MSG="chore(rank): update cfbrank.json $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git commit -m "$MSG"
          git push origin HEAD:${{ github.event.inputs.target_branch || 'main' }}
